In [1]:
# Load NumPy Library 
import numpy as np 


In [2]:
vector_row = np.array([1, 2, 3])
print(vector_row) 

[1 2 3]


In [3]:
# Create a vector as column 
vector_column = np.array([[1], [2], [3]]) 
print(vector_column)

[[1]
 [2]
 [3]]


In [4]:
mat1 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
print(mat1)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [5]:
mat2 = np.array([[1, 2], [3,4], [4, 6]])
print(mat2) 

[[1 2]
 [3 4]
 [4 6]]


In [6]:
mat3 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
mat3.shape

(3, 4)

In [7]:
mat3.shape[0]

3

In [8]:
mat3.shape[1]

4

In [9]:
mat4 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")

In [10]:
mat4.size

12

In [11]:
mat5 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
print(mat5)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [12]:
# adding a new matrix `col_new` as a new column to mat5
col_new = np.matrix("1, 1, 1")
print(col_new)

[[1 1 1]]


In [13]:


# insert at column 
mat6 = np.insert(mat5, 0, col_new, axis=1)
print(mat6) 



[[ 1  1  2  3  4]
 [ 1  4  5  6  7]
 [ 1  7  8  9 10]]


In [14]:


# adding a new matrix `row_new` as a new row to mat5
row_new = np.matrix("0, 0, 0, 0")
print(row_new)



[[0 0 0 0]]


In [15]:
# insert at row 
mat7 = np.insert(mat5, 0, row_new, axis=0)
print(mat7)

[[ 0  0  0  0]
 [ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [16]:


mat_a = np.matrix("1, 2, 3, 4, 5; 5, 6, 7, 8, 9; 9, 10, 11, 12, 13")
print(mat_a)



[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [17]:


# change 6 with 0 
mat_a[1, 1] = 0 


In [18]:
# show mat_a 
print(mat_a)

[[ 1  2  3  4  5]
 [ 5  0  7  8  9]
 [ 9 10 11 12 13]]


In [19]:
# extract 2nd row 
mat_a[1, :]

matrix([[5, 0, 7, 8, 9]])

In [20]:
mat_a.shape

(3, 5)

In [21]:
mat_a[:, 2]

matrix([[ 3],
        [ 7],
        [11]])

In [22]:
mat_a[1, 2]

7

In [23]:
A = np.arange(0, 20).reshape(5,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [25]:
print(type(A))

<class 'numpy.ndarray'>


In [26]:
B = np.arange(20, 40).reshape(5,4)
print(B)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [27]:
np.add(A, B)

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [28]:
np.subtract(A,B)

array([[-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20]])

In [29]:
    

A = np.arange(0, 20).reshape(5,4)
print(A)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [32]:


# transpose 
np.transpose(A)


array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [31]:
np.dot(A,B)

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [33]:
print(A.shape,B.shape)

(5, 4) (5, 4)


In [34]:


# transpose matrix B to make it 4x5 in dimension
T = np.transpose(B)
print(T)



[[20 24 28 32 36]
 [21 25 29 33 37]
 [22 26 30 34 38]
 [23 27 31 35 39]]


In [35]:
np.dot(A,T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [36]:


# using matmul 
np.matmul(A, T)



array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [37]:
# using @ operator 
A @ T 

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [38]:


# element-wise multiplication 
np.multiply(A, B)



array([[  0,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525],
       [576, 629, 684, 741]])

In [39]:
np.divide(A, B)

array([[0.        , 0.04761905, 0.09090909, 0.13043478],
       [0.16666667, 0.2       , 0.23076923, 0.25925926],
       [0.28571429, 0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

In [43]:
print(A,'\n\n',B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

 [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
